// Mapping of classes to be replaced
module.exports = {
    // colors
    "color-black": "color-neutral-1200",
    "color-white": "color-neutral-100",
    "color-charcoal": "color-neutral-1000",
    "color-charcoal-dark": "color-neutral-1000",
    "color-dimGray": "color-neutral-900",
    "color-darkGray": "color-neutral-800",
    "color-silver": "color-neutral-700",
    "color-lightGray": "color-neutral-600",
    "color-gainsBoroGray": "color-neutral-500",
    "color-whiteSmoke": "color-neutral-400",
    "color-whiteSmokeLight": "color-neutral-200",
    "color-dimWhite": "color-neutral-300",
    "color-gothic": "color-misc-300",
    "color-blackRussian": "color-misc-500",
    "color-edenBlue": "color-misc-400",
    "color-mediumBrown": "color-info-900",
    "color-redRose": "color-primary-300",
    "color-offBrown": "color-info-300",
    "color-brightTurquoise": "color-misc-200",
    "color-aquaTeal": "color-secondary-300",
    "color-teal-lightest": "color-secondary-400",
    "color-teal-light": "color-secondary-700",
    "color-teal": "color-secondary-900",
    "color-teal-dark": "color-secondary-1000",
    "color-red-lightest": "color-primary-400",
    "color-red-light": "color-primary-700",
    "color-red": "color-primary-900",
    "color-red-dark": "color-primary-1000",
    "color-red-darkest": "color-primary-1100",
    "color-brown-light": "color-info-500",
    "color-brown": "color-info-700",
    "color-brown-dark": "color-info-1000",
    "color-brown-darkest": "color-info-1100",
    "color-blue-lightest": "color-accent-700",
    "color-blue-light": "color-accent-800",
    "color-blue": "color-accent-900",
    "color-blue-dark": "color-accent-1000",
    "color-blue-darkest": "color-accent-1100",
    "color-transparent": "color-misc-100",

    // stroke
    "stroke-charcoal": "stroke-neutral-900",
    "stroke-charcoal-dark": "stroke-neutral-1000",
    "stroke-teal": "stroke-secondary-900",
    "stroke-red": "stroke-primary-900",
    "stroke-brown": "stroke-info-700",
    "stroke-blue": "stroke-accent-900",
    "stroke-lightGray": "stroke-neutral-600",

    // bg color
    "bg-aquaTeal": "bg-secondary-300",
    "bg-transparent": "bg-misc-100",
    "bg-black": "bg-neutral-1200",
    "bg-white": "bg-neutral-100",
    "bg-dimGray": "bg-neutral-800", // remove later added for test testing only
    "bg-darkGray": "bg-neutral-800",
    "bg-lightGray": "bg-neutral-600",
    "bg-gainsBoroGray": "bg-neutral-500",
    "bg-whiteSmoke": "bg-neutral-400",
    "bg-whiteSmokeLight": "bg-neutral-200",
    "bg-dimWhite": "bg-neutral-200", // remove later added for test testing only
    "bg-gothic": "bg-misc-300",
    "bg-blackRussian": "bg-misc-500",
    "bg-edenBlue": "bg-misc-400",
    "bg-offBrown": "bg-info-300",
    "bg-teal-lightest": "bg-secondary-400",
    "bg-teal-light": "bg-secondary-700",
    "bg-teal": "bg-secondary-900",
    "bg-teal-dark": "bg-secondary-1000",
    "bg-brown-light": "bg-info-500",
    "bg-brown": "bg-info-700",
    "bg-brown-dark": "bg-info-1000",
    "bg-brown-darkest": "bg-info-1100",
    "bg-red-lightest": "bg-primary-400",
    "bg-red-light": "bg-primary-700",
    "bg-red": "bg-primary-900",
    "bg-red-dark": "bg-primary-1000",
    "bg-red-darkest": "bg-primary-1100",
    "bg-redRose": "bg-primary-300",
    "bg-blue-lightest": "bg-accent-700",
    "bg-blue-light": "bg-accent-800",
    "bg-blue": "bg-accent-900",
    "bg-blue-dark": "bg-accent-1000",
    "bg-light-blue-base": "bg-accent-400", // TODO: check this
    "bg-blue-darkest": "bg-accent-1100",
    "bg-charcoal": "bg-neutral-900",
    "bg-silver": "bg-neutral-700",
    "bg-azure": "bg-secondary-300",

    // bg-with-opacity
    "bg-black-10": "bg-neutral-1200-10",
    "bg-black-25": "bg-neutral-1200-25",
    "bg-black-50": "bg-neutral-1200-50",
    "bg-black-75": "bg-neutral-1200-75",
    "bg-black-90": "bg-neutral-1200-90",
    "bg-white-10": "bg-neutral-100-10",
    "bg-white-25": "bg-neutral-100-25",
    "bg-white-50": "bg-neutral-100-50",
    "bg-white-75": "bg-neutral-100-75",
    "bg-white-90": "bg-neutral-100-90",

    // Gradient
    "bg-gradient-charcoal-light": "bg-gradient-neutral-1000",
    "bg-gradient-charcoal-light-reverse": "bg-gradient-neutral-1000-reverse",
    "bg-gradient-charcoal": "bg-gradient-neutral-1000-dark",
    "bg-gradient-charcoal-dark": "bg-gradient-neutral-1200",
    "bg-gradient-charcoal-dark-left": "bg-gradient-neutral-1000-left",
    "bg-gradient-black-reverse": "bg-gradient-neutral-1000-light",
    "bg-gradient-red-light-reverse": "bg-gradient-primary-900",

    // border
    "border-color-transparent": "border-color-misc-100",
    "border-color-white": "border-color-neutral-100",
    "border-color-dimGray": "border-color-neutral-800", // remove later added for test testing only
    "border-color-darkGray": "border-color-neutral-800",
    "border-color-silver": "border-color-neutral-700",
    "border-color-lightGray": "border-color-neutral-600",
    "border-color-gainsBoroGray": "border-color-neutral-500",
    "border-color-whiteSmoke": "border-color-neutral-500", // remove later added for test testing only
    "border-color-gothic": "border-color-misc-300",
    "border-color-edenBlue": "border-color-misc-400",
    "border-color-teal": "border-color-secondary-900",
    "border-color-red": "border-color-primary-900",
    "border-color-red-lightest": "border-color-primary-400",
    "border-color-brown-light": "border-color-info-500",
    "border-color-blue-lightest": "border-color-accent-700",
    "border-color-mediumBrown": "border-color-info-900",
    "border-color-brown": "border-color-info-700",
    "border-color-teal-lightest": "border-color-secondary-400",
    "border-color-teal-light": "border-color-secondary-700",
    "border-color-riptide": "border-color-secondary-700",
    "border-color-mabel": "border-color-teal-lightest",
    "border-color-blue-darkest": "border-color-accent-1100",
    "border-color-blue-light": "border-color-accent-800",
    "border-color-blue": "border-color-accent-900",
    "border-color-black": "border-color-neutral-1200",
    "border-color-teal-dark": "border-color-secondary-1000",
};
