// Mapping of classes to be replaced
module.exports = {
    /* Neutral */
    "color-black": "neutral-1200",
    "color-charcoal-dark": "neutral-1100",
    "color-charcoal": "neutral-1000",
    "color-dimGray": "neutral-900",
    "color-darkGray": "neutral-800",
    "color-silver": "neutral-700",
    "color-lightGray": "neutral-600",
    "color-gainsBoroGray": "neutral-500",
    "color-whiteSmoke": "neutral-400",
    "color-dimWhite": "neutral-300",
    "color-whiteSmokeLight": "neutral-200",
    "color-white": "neutral-100",
    /* info */
    "color-brown-darkest": "info-1100",
    "color-brown-dark": "info-1000",
    "color-mediumBrown": "info-900",
    "color-brown": "info-700",
    "color-brown-light": "info-500",
    "color-offBrown": "info-300",
    /* Accent / Brand */
    "color-blue-darkest": "accent-1100",
    "color-blue-dark": "accent-1000",
    "color-blue": "accent-900",
    "color-blue-light": "accent-800",
    "color-light-blue-base": "accent-400",
    /* Secondary */
    "color-teal-dark": "secondary-1000",
    "color-teal": "secondary-900",
    "color-teal-light": "secondary-700",
    "color-teal-lightest": "secondary-400",
    "color-aquaTeal": "secondary-300",
    /* Primary */
    "color-red-darkest": "primary-1100",
    "color-red-dark": "primary-1000",
    "color-red": "primary-900",
    "color-red-light": "primary-700",
    "color-red-lightest": "primary-400",
    "color-red-redRose": "primary-300",
    /* Misc */
    "color-blackRussian": "misc-500",
    "color-edenBlue": "misc-400",
    "color-gothic": "misc-300",
    "color-brightTurquoise": "misc-200",
    "color-transparent": "misc-100",
    /* Border Neutral */
    "border-color-black": "neutral-1200",
    "border-color-charcoal-dark": "neutral-1100",
    "border-color-charcoal": "neutral-1000",
    "border-color-dimGray": "neutral-900",
    "border-color-darkGray": "neutral-800",
    "border-color-silver": "neutral-700",
    "border-color-lightGray": "neutral-600",
    "border-color-gainsBoroGray": "neutral-500",
    "border-color-whiteSmoke": "neutral-400",
    "border-color-dimWhite": "neutral-300",
    "border-color-whiteSmokeLight": "neutral-200",
    "border-color-white": "neutral-100",
    /* info */
    "border-color-brown-darkest": "info-1100",
    "border-color-brown-dark": "info-1000",
    "border-color-mediumBrown": "info-900",
    "border-color-brown": "info-700",
    "border-color-brown-light": "info-500",
    "border-color-offBrown": "info-300",
    /* Accent / Brand */
    "border-color-blue-darkest": "accent-1100",
    "border-color-blue-dark": "accent-1000",
    "border-color-blue": "accent-900",
    "border-color-blue-light": "accent-800",
    "border-color-light-blue-base": "accent-400",
    /* Secondary */
    "border-color-teal-dark": "secondary-1000",
    "border-color-teal": "secondary-900",
    "border-color-teal-light": "secondary-700",
    "border-color-teal-lightest": "secondary-400",
    "border-color-aquaTeal": "secondary-300",
    /* Primary */
    "border-color-red-darkest": "primary-1100",
    "border-color-red-dark": "primary-1000",
    "border-color-red": "primary-900",
    "border-color-red-light": "primary-700",
    "border-color-red-lightest": "primary-400",
    "border-color-red-redRose": "primary-300",
    /* Misc */
    "border-color-blackRussian": "misc-500",
    "border-color-edenBlue": "misc-400",
    "border-color-gothic": "misc-300",
    "border-color-brightTurquoise": "misc-200",
    "border-color-transparent": "misc-100",
    /* BG Neutral */
    "bg-black": "neutral-1200",
    "bg-charcoal-dark": "neutral-1100",
    "bg-charcoal": "neutral-1000",
    "bg-dimGray": "neutral-900",
    "bg-darkGray": "neutral-800",
    "bg-silver": "neutral-700",
    "bg-lightGray": "neutral-600",
    "bg-gainsBoroGray": "neutral-500",
    "bg-whiteSmoke": "neutral-400",
    "bg-dimWhite": "neutral-300",
    "bg-whiteSmokeLight": "neutral-200",
    "bg-white": "neutral-100",
    /* info */
    "bg-brown-darkest": "info-1100",
    "bg-brown-dark": "info-1000",
    "bg-mediumBrown": "info-900",
    "bg-brown": "info-700",
    "bg-brown-light": "info-500",
    "bg-offBrown": "info-300",
    /* Accent / Brand */
    "bg-blue-darkest": "accent-1100",
    "bg-blue-dark": "accent-1000",
    "bg-blue": "accent-900",
    "bg-blue-light": "accent-800",
    "bg-light-blue-base": "accent-400",
    /* Secondary */
    "bg-teal-dark": "secondary-1000",
    "bg-teal": "secondary-900",
    "bg-teal-light": "secondary-700",
    "bg-teal-lightest": "secondary-400",
    "bg-aquaTeal": "secondary-300",
    /* Primary */
    "bg-red-darkest": "primary-1100",
    "bg-red-dark": "primary-1000",
    "bg-red": "primary-900",
    "bg-red-light": "primary-700",
    "bg-red-lightest": "primary-400",
    "bg-red-redRose": "primary-300",
    /* Misc */
    "bg-blackRussian": "misc-500",
    "bg-edenBlue": "misc-400",
    "bg-gothic": "misc-300",
    "bg-brightTurquoise": "misc-200",
    "bg-transparent": "misc-100",
    /* Gradient */
    "bg-gradient-charcoal-light": "bg-gradient-neutral-1000",
    "bg-gradient-charcoal-light-reverse": "bg-gradient-neutral-1000-reverse",
    "bg-gradient-charcoal": "bg-gradient-neutral-1000-dark",
    "bg-gradient-charcoal-dark": "bg-gradient-neutral-1200",
    "bg-gradient-charcoal-dark-left": "bg-gradient-neutral-1200-left",
    "bg-gradient-black-reverse": "bg-gradient-neutral-1200-light",
    "bg-gradient-red-light-reverse": "bg-gradient-primary-900",
};